name: Update README with latest activity

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Update README with latest GitHub activity
      uses: jamesgeorge007/github-activity-readme@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        COMMIT_MSG: 'Updated README with latest activity'
        MAX_LINES: 8
